language: java
dist: trusty

language: java
jdk:
  - oraclejdk8

before_install:
 - chmod +x gradlew

install: true
script: "./gradlew build -x copyDistFiles"

script:
  - ./gradlew clean build test

notifications:
 email:
   on_failure: always
   recipients:
      - treadz11@gmail.com